(function(){'use strict';document.querySelectorAll('[data-inspection-compare]').forEach(root=>{
 const stage=root.querySelector('.comparison-stage'),range=root.querySelector('.comparison-range'),before=root.querySelector('.comparison-before'),divider=root.querySelector('.comparison-divider'),status=root.querySelector('[data-comparison-status]'),buttons=root.querySelectorAll('[data-compare-view]');
 function set(value,side=false){value=Math.max(0,Math.min(100,Number(value)));stage.classList.toggle('is-side-by-side',side);range.disabled=side;range.value=String(value);before.style.clipPath=side?'none':`inset(0 ${100-value}% 0 0)`;divider.style.left=value+'%';root.querySelector('#comparison-help').textContent=side?'Side-by-side view. Choose Split view to use the comparison slider.':'Drag across the image, or focus the comparison and use the arrow keys. Home and End reveal either illustration.';range.setAttribute('aria-valuetext',`${value}% buildup illustration and ${100-value}% clean-wall illustration`);status.textContent=side?'Both illustrations shown separately.':`${value}% buildup · ${100-value}% clean wall`;buttons.forEach(b=>b.setAttribute('aria-pressed',String(side?b.dataset.compareView==='side':Number(b.dataset.compareView)===value)))}
 range.addEventListener('input',()=>set(range.value));buttons.forEach(b=>b.addEventListener('click',()=>{set(b.dataset.compareView==='side'?50:b.dataset.compareView,b.dataset.compareView==='side');window.ProJetCinema?.cue('tap')}));set(50);
 // Paired video support is inactive for the illustrative stills. Playback is manual.
 const videos=[...root.querySelectorAll('video')],controls=root.querySelector('.comparison-video-controls');if(videos.length!==2||!controls)return;
 const time=controls.querySelector('input'),play=controls.querySelector('button');let ready=false;
 function pause(){videos.forEach(v=>v.pause());play.textContent='Play inspection pair'}
 function metadata(){const duration=Math.min(...videos.map(v=>v.duration));ready=Number.isFinite(duration)&&duration>0;if(ready){controls.hidden=false;time.max=String(duration)}}
 videos.forEach(v=>{v.muted=true;v.loop=false;v.addEventListener('loadedmetadata',metadata);v.addEventListener('ended',pause);v.addEventListener('error',()=>{pause();controls.hidden=true;status.textContent='Inspection media unavailable.'})});
 play.addEventListener('click',async()=>{if(!ready)return;if(!videos[0].paused){pause();return}if(videos[0].currentTime>=Number(time.max)-.1)videos.forEach(v=>v.currentTime=0);try{await Promise.all(videos.map(v=>v.play()));play.textContent='Pause inspections'}catch(_){pause();status.textContent='Playback unavailable; use the still comparison.'}});
 videos[0].addEventListener('timeupdate',()=>{time.value=String(videos[0].currentTime);if(Math.abs(videos[1].currentTime-videos[0].currentTime)>.2)videos[1].currentTime=videos[0].currentTime;if(videos[0].currentTime>=Number(time.max)-.04)pause()});
 time.addEventListener('input',()=>{pause();videos.forEach(v=>v.currentTime=Math.min(Number(time.value),Number(time.max)))});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});metadata();
});})();
